export const demoIssueBlueprints = [
  {
    publicId: "CV-1024",
    category: "POTHOLE",
    zone: "NORTH",
    title: "Large pothole on Sayyaji Rao Road near Mission Hospital",
    description: "Deep pothole forming on the northbound carriageway. Two-wheelers forced to swerve abruptly into oncoming traffic.",
    coordinates: [76.6412, 12.3245],
    status: "IN_PROGRESS",
    priority: "HIGH",
    verificationStatus: "VERIFIED_WITH_LOW_RISK",
    verificationScore: 92,
    supportCount: 14,
    officerEmail: "ananya.officer@mysuru.gov.in",
  },
  {
    publicId: "CV-1025",
    category: "GARBAGE",
    zone: "CENTRAL",
    title: "Overflowing commercial garbage at Devaraja Market North Gate",
    description: "Huge accumulation of organic vegetable waste and rotten packaging obstructing the pedestrian pathway and drain.",
    coordinates: [76.6508, 12.3116],
    status: "ESCALATED",
    priority: "CRITICAL",
    verificationStatus: "VERIFIED_WITH_LOW_RISK",
    verificationScore: 89,
    supportCount: 26,
    escalated: true,
    escalationReason: "Exceeded 12-hour critical SLA deadline for central commercial market area.",
    officerEmail: "commissioner@mysuru.gov.in",
  },
  {
    publicId: "CV-1026",
    category: "STREETLIGHT",
    zone: "WEST",
    title: "Broken sodium vapor streetlight in Kuvempunagar M-Block",
    description: "Pole #KP-42 flickering and completely dark at night near the community park, creating safety concerns for senior walkers.",
    coordinates: [76.6215, 12.2882],
    status: "RESOLVED",
    priority: "MEDIUM",
    verificationStatus: "VERIFIED_WITH_LOW_RISK",
    verificationScore: 86,
    supportCount: 8,
    resolvedAt: new Date(Date.now() - 4 * 3600000),
    officerEmail: "karthik.officer@mysuru.gov.in",
    hasResolutionEvidence: true,
  },
  {
    publicId: "CV-1027",
    category: "DRAIN",
    zone: "EAST",
    title: "Suspicious / unverified drain report with low location accuracy",
    description: "Citizen reported blocked storm water drain, but browser GPS accuracy was ±350m and image showed potential web stock photo.",
    coordinates: [76.6852, 12.3021],
    status: "NEEDS_REVIEW",
    priority: "CRITICAL",
    verificationStatus: "INSUFFICIENT_OR_SUSPICIOUS",
    verificationScore: 38,
    supportCount: 1,
    officerEmail: "commissioner@mysuru.gov.in",
  },
];
